	.align 2
voicegroup191::
	voice_keysplit_all voicegroup001
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw2_classic_trumpet, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_bw2_frhorn_1, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_bw2_frhorn_2, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_grv_crash, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_bw2_strings, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_bw2_tubbell, 255, 0, 255, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0

