gText_Birch_Welcome::
	.string "Let's see, where are my notes...\p"
	.string "Oh, here we go.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Welcome to Orre. One of the more\n"
	.string "recently-settled places in history,\p"
	.string "this ol' patch of heaven has,\n"
	.string "for the longest time, not exactly been\l"
	.string "teeming with Pokémon.\p"
	.string "In fact, Pokémon as a whole\n"
	.string "basically amounted to occasional\l"
	.string "migratory species coming and going.\p"
	.string "Over the last few years though,\n"
	.string "concerted conservation efforts have\l"
	.string "turned what started as just a few\l"
	.string "isolated “Poké Spots” into true,\l"
	.string "diverse biosystems full of Pokémon.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Problem being... we're not entirely\n"
	.string "sure just what's been coming in.\p"
	.string "After an invasive Durant incident,\n"
	.string "we figured it was time to actually\l"
	.string "start cataloguing what we've got.\p"
	.string "That's where you come in, kid.\p"
	.string "...What? No, I don't care how old\n"
	.string "you actually are, when you're my age,\l"
	.string "everyone's a kid.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Ah, I haven't actually introduced\n"
	.string "myself properly, have I?\l"
	.string "I'm Professor Mesquite.\p"
	.string "I guess I'm the head of Orre's new\n"
	.string "Pokédex Extended Fileshare Endeavor\l"
	.string "branch now.\p"
	.string "Anyway, grab your Trainer card\n"
	.string "and your Pokédex, get out there,\l"
	.string "and see if you can't ID just what\l"
	.string "sort of life is growing out there\l"
	.string "in Orre's desert these days.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Make sure everything's printed\n"
	.string "right on your card.$"

gText_Birch_WhatsYourName::
	.string "$"

gText_Birch_SoItsPlayer::
	.string "All set, {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Great. Let's get on with it.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "We'll start you out easy,\n"
	.string "sending you off to Agate Village\l"
	.string "instead of dropping you right\l"
	.string "into the heat of the desert.\p"
	.string "Still, don't forget to drink\n"
	.string "lots of water. And don't\l"
	.string "make fun of people's names.\p"
	.string "That'll out you as a “tourist”\n"
	.string "real quick.\p"
	.string "$"
